version: '3.8'
services:
  backend:
    build: ./backend
    ports: 
      - "8000:8000"
    environment: 
      - PORT=8000 
    volumes:
      - ./backend:/app

  frontend:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
